apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
    project: k8straining
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
        project: k8straining
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: PASSWORD_1
          valueFrom:
            secretKeyRef:
              name: yaml-based
              key: password1
        - name: PASSWORD_2
          valueFrom:
            secretKeyRef:
              name: yaml-based
              key: password2
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        secret:
          secretName: file-based
