apiVersion: v1
kind: Secret
metadata:
  name: yaml-based
  labels:
    app: kuard
    project: k8straining
data:
  password1: "c3VwZXJTZWNyZXRQYXNzd29yZA=="
  password2: "YW5vdGhlclN1cGVyU2VjcmV0UGFzc3dvcmQ="
