apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
    layer: backend
    project: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: drupal
    layer: backend
    project: wordpress
  type: LoadBalancer
