apiVersion: v1
kind: Service
metadata:
  name: etherpad
  labels:
    app: etherpad
    layer: backend
    project: etherpad
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: etherpad
    layer: backend
    project: etherpad
  type: LoadBalancer
