apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    layer: db
    project: etherpad
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    layer: db
    project: etherpad
  type: ClusterIP
