kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd"
  labels:
    app: mysql
    layer: db
    project: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
